// <auto-generated />
using System;
using BPAMatchineTrack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BPAMatchineTrack.Migrations
{
    [DbContext(typeof(CottonclubContext))]
    partial class CottonclubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BPAMachineTrack.Models.tbl_Layout", b =>
                {
                    b.Property<int>("SLNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLNO"));

                    b.Property<DateTime?>("DATE")
                        .HasColumnType("datetime");

                    b.Property<int?>("LID")
                        .HasColumnType("int");

                    b.Property<string>("LOCATION_DETAILS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MCID")
                        .HasColumnType("int");

                    b.Property<int?>("OCID")
                        .HasColumnType("int");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLNO");

                    b.HasIndex("OCID");

                    b.ToTable("tbl_Layout", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblBrandInformation", b =>
                {
                    b.Property<int>("Brid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Brid"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Brid");

                    b.ToTable("tbl_Brand_Information", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblBuildingInfo", b =>
                {
                    b.Property<int>("Buid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BUID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Buid"));

                    b.Property<int?>("Cid")
                        .HasColumnType("int")
                        .HasColumnName("CID");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Opt1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Buid");

                    b.HasIndex("Cid");

                    b.ToTable("tbl_Building_Info", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblCompanyInfo", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cid"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Company_Name");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Opt1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Short_Name");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cid");

                    b.ToTable("tbl_Company_Info", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblFloorInfo", b =>
                {
                    b.Property<int>("Fid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Fid"));

                    b.Property<int?>("Buid")
                        .HasColumnType("int")
                        .HasColumnName("BUID");

                    b.Property<int?>("Cid")
                        .HasColumnType("int")
                        .HasColumnName("CID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Fid");

                    b.HasIndex("Buid");

                    b.HasIndex("Cid");

                    b.ToTable("tbl_Floor_Info", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblMachineTypeInfo", b =>
                {
                    b.Property<int>("Mtid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mtid"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mtid");

                    b.ToTable("tbl_Machine_Type_Info", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblMcLocation", b =>
                {
                    b.Property<int>("Lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lid"));

                    b.Property<int?>("Buid")
                        .HasColumnType("int");

                    b.Property<int?>("Cid")
                        .HasColumnType("int");

                    b.Property<int?>("Fid")
                        .HasColumnType("int");

                    b.Property<int?>("FidNavigationFid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Lid");

                    b.HasIndex("Buid");

                    b.HasIndex("Cid");

                    b.HasIndex("FidNavigationFid");

                    b.ToTable("tbl_MC_Location", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblScanInformation", b =>
                {
                    b.Property<int>("Scid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SCID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Scid"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Lid")
                        .HasColumnType("int");

                    b.Property<string>("Opt1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opt3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Scdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SCDate");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Scid");

                    b.ToTable("tbl_Scan_Information", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Extra_MC_Req_D", b =>
                {
                    b.Property<int>("TRNSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TRNSID"));

                    b.Property<decimal?>("Capacity")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("Exist_Qty")
                        .HasColumnType("numeric(18,0)");

                    b.Property<int?>("MTID")
                        .HasColumnType("int");

                    b.Property<decimal?>("QTY")
                        .HasColumnType("numeric(18,0)");

                    b.Property<int?>("RID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TRNSDATE")
                        .HasColumnType("datetime");

                    b.HasKey("TRNSID");

                    b.HasIndex("RID");

                    b.ToTable("tbl_Extra_MC_Req_D", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Extra_MC_Requisition", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RID"));

                    b.Property<string>("AUTH_BY")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BOOKING_NO")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BUID")
                        .HasColumnType("int");

                    b.Property<string>("CHECKED_BY")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<int?>("FID")
                        .HasColumnType("int");

                    b.Property<int?>("LID")
                        .HasColumnType("int");

                    b.Property<string>("OPT1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PREPARE_BY")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("RDATE")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("REQUIRED_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("REQ_FOR")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RID");

                    b.ToTable("tbl_Extra_MC_Requisition", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Machine_Detail", b =>
                {
                    b.Property<int>("MCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MCID"));

                    b.Property<int?>("BRID")
                        .HasColumnType("int");

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<string>("Capaity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MCNO")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("MTID")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_System")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Rcv_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRNO")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MCID");

                    b.HasIndex("BRID");

                    b.HasIndex("CID");

                    b.HasIndex("MTID");

                    b.ToTable("tbl_Machine_Details");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Other_Company", b =>
                {
                    b.Property<int>("OCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OCID"));

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTRACT_PERSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OC_NAME")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("REMARKS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OCID");

                    b.ToTable("tbl_Other_Company", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Rent_MC_Req_D", b =>
                {
                    b.Property<int>("TRNSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TRNSID"));

                    b.Property<int?>("MTID")
                        .HasColumnType("int");

                    b.Property<decimal?>("QTY")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("REMARKS")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("RID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TRNSDATE")
                        .HasColumnType("datetime");

                    b.HasKey("TRNSID");

                    b.ToTable("tbl_Rent_MC_Req_D", (string)null);
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Rent_MC_Requisition", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RID"));

                    b.Property<string>("AUTH_BY")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BOOKING_NO")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BUID")
                        .HasColumnType("int");

                    b.Property<string>("CHECKED_BY")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<int?>("FID")
                        .HasColumnType("int");

                    b.Property<int?>("LID")
                        .HasColumnType("int");

                    b.Property<string>("OPT1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PREPARE_BY")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("RDATE")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("REQUIRED_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("REQ_FOR")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RID");

                    b.HasIndex("CID");

                    b.ToTable("tbl_Rent_MC_Requisition", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BPAMachineTrack.Models.tbl_Layout", b =>
                {
                    b.HasOne("BPAMatchineTrack.Models.tbl_Other_Company", "OtherCompany")
                        .WithMany("Layouts")
                        .HasForeignKey("OCID");

                    b.Navigation("OtherCompany");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblBuildingInfo", b =>
                {
                    b.HasOne("BPAMatchineTrack.Models.TblCompanyInfo", "CidNavigation")
                        .WithMany("TblBuildingInfos")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK_tbl_Building_Info_tbl_Company_Info");

                    b.Navigation("CidNavigation");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblFloorInfo", b =>
                {
                    b.HasOne("BPAMatchineTrack.Models.TblBuildingInfo", "Bu")
                        .WithMany("TblFloorInfos")
                        .HasForeignKey("Buid");

                    b.HasOne("BPAMatchineTrack.Models.TblCompanyInfo", "CidNavigation")
                        .WithMany("TblFloorInfos")
                        .HasForeignKey("Cid");

                    b.Navigation("Bu");

                    b.Navigation("CidNavigation");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblMcLocation", b =>
                {
                    b.HasOne("BPAMatchineTrack.Models.TblBuildingInfo", "Bu")
                        .WithMany("TblMcLocations")
                        .HasForeignKey("Buid");

                    b.HasOne("BPAMatchineTrack.Models.TblCompanyInfo", "CidNavigation")
                        .WithMany("TblMcLocations")
                        .HasForeignKey("Cid");

                    b.HasOne("BPAMatchineTrack.Models.TblFloorInfo", "FidNavigation")
                        .WithMany("TblMcLocations")
                        .HasForeignKey("FidNavigationFid");

                    b.Navigation("Bu");

                    b.Navigation("CidNavigation");

                    b.Navigation("FidNavigation");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Extra_MC_Req_D", b =>
                {
                    b.HasOne("BPAMatchineTrack.Models.tbl_Extra_MC_Requisition", "RIDNavigation")
                        .WithMany("tbl_Extra_MC_Req_Ds")
                        .HasForeignKey("RID")
                        .HasConstraintName("FK_tbl_Extra_MC_Req_D_tbl_Extra_MC_Requisition");

                    b.Navigation("RIDNavigation");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Machine_Detail", b =>
                {
                    b.HasOne("BPAMatchineTrack.Models.TblBrandInformation", "BR")
                        .WithMany("tbl_Machine_Details")
                        .HasForeignKey("BRID");

                    b.HasOne("BPAMatchineTrack.Models.TblCompanyInfo", "CIDNavigation")
                        .WithMany("tbl_Machine_Details")
                        .HasForeignKey("CID");

                    b.HasOne("BPAMatchineTrack.Models.TblMachineTypeInfo", "MT")
                        .WithMany("tbl_Machine_Details")
                        .HasForeignKey("MTID");

                    b.Navigation("BR");

                    b.Navigation("CIDNavigation");

                    b.Navigation("MT");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Rent_MC_Requisition", b =>
                {
                    b.HasOne("BPAMatchineTrack.Models.TblCompanyInfo", "Company")
                        .WithMany()
                        .HasForeignKey("CID");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblBrandInformation", b =>
                {
                    b.Navigation("tbl_Machine_Details");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblBuildingInfo", b =>
                {
                    b.Navigation("TblFloorInfos");

                    b.Navigation("TblMcLocations");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblCompanyInfo", b =>
                {
                    b.Navigation("TblBuildingInfos");

                    b.Navigation("TblFloorInfos");

                    b.Navigation("TblMcLocations");

                    b.Navigation("tbl_Machine_Details");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblFloorInfo", b =>
                {
                    b.Navigation("TblMcLocations");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.TblMachineTypeInfo", b =>
                {
                    b.Navigation("tbl_Machine_Details");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Extra_MC_Requisition", b =>
                {
                    b.Navigation("tbl_Extra_MC_Req_Ds");
                });

            modelBuilder.Entity("BPAMatchineTrack.Models.tbl_Other_Company", b =>
                {
                    b.Navigation("Layouts");
                });
#pragma warning restore 612, 618
        }
    }
}
